package ru.javaprojects.thinkinginjava.chapter15.exercise36;

public class Failure2 extends Exception {
}
